name: help_desk_app
description: Olá Mundo! Bem vindo ao HelpDesk, um aplicativo mobile feito com a linguagem Flutter e Dart, juntamente com o banco de dados Firebase.

version: 1.0.0+1

environment:
  sdk: '>=3.0.0-204.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  firebase_core: ^2.7.0     # Ativa os recursos padrão do firebase
  firebase_auth: ^4.2.9     # Permite utilizar os recursos de autenticação do firebase
  cloud_firestore: ^4.4.3   # Permite utilizar o banco de dados cloud firestore
  google_fonts: ^4.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
